stages:
  - install
  - test
  - build
  - deploy

# instalar dependencias

install_dependencias:
  stage: install
  image: node:20
  script:
    - npm install
  cache:
    paths:
      - node_modules/

# Ejecucion de pruebas
run_tests:
  stage: test
  image: node:20
  script:
    - npm test

# constuir el proyecto
build_project:
  stage: build
  image: node:20
  script:
    - npm build
  artifacts:
  paths:
    - .next/
  expire_in: 1 day

# deploy
default:
  image: node:16.16.0
deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
